-- Migration: 15_create_ai_history.sql
-- Description: Create table to persist AI generation history (Farol, Marketing, Legal)

create table if not exists public.ai_history (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    inscricao text not null,
    type text not null, -- 'MARKETING', 'VALUATION', 'LEGAL', 'CHAT'
    content text,
    metadata jsonb default '{}'::jsonb -- For storing extra context like prompts used
);

-- Index for fast lookup by unit
create index if not exists ai_history_inscricao_idx on public.ai_history (inscricao);

-- Enable RLS
alter table public.ai_history enable row level security;

-- Policies
-- 1. Allow everyone to read (since this is an internal tool usage context)
create policy "Enable read access for all users"
on public.ai_history
for select
using (true);

-- 2. Allow everyone to insert
create policy "Enable insert access for all users"
on public.ai_history
for insert
with check (true);

-- 3. Allow deletion (optional, maybe restricts to admin later)
create policy "Enable delete access for all users"
on public.ai_history
for delete
using (true);
