-- Add Unit-specific columns
ALTER TABLE unidades 
ADD COLUMN IF NOT EXISTS suites INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS banheiros INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS vagas INTEGER DEFAULT 0;

-- Add Building-specific columns (Amenities) to LOTES table
-- These are boolean flags or text for the building
ALTER TABLE lotes 
ADD COLUMN IF NOT EXISTS elevador BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS portaria_24h BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS churrasqueira BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS salao_jogos BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS servico_praia BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS zeladoria BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS piscina BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS academia BOOLEAN DEFAULT FALSE;

-- Notify PostgREST to reload schema
NOTIFY pgrst, 'reload config';
